// <auto-generated />
using System;
using GameOfThrones.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfThrones.Api.Migrations
{
    [DbContext(typeof(GameOfThronesDbContext))]
    [Migration("20260808191139_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameOfThrones.Api.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CurrentAllegiance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("FirstEpisodeAppearance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KilledById")
                        .HasColumnType("int");

                    b.Property<string>("LastEpisodeAppearance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpouseId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("HouseId");

                    b.HasIndex("KilledById");

                    b.HasIndex("MotherId");

                    b.HasIndex("SpouseId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorName = "Kit Harington",
                            CurrentAllegiance = "House Stark",
                            FirstEpisodeAppearance = "Winter Is Coming",
                            FirstName = "Jon",
                            Gender = 1,
                            HouseId = 1,
                            ImagePath = "/images/characters/jon-snow.png",
                            LastEpisodeAppearance = "The Iron Throne",
                            LastName = "Snow",
                            Nickname = "King in the North",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorName = "Peter Dinklage",
                            CurrentAllegiance = "House Lannister",
                            FirstEpisodeAppearance = "Winter Is Coming",
                            FirstName = "Tyrion",
                            Gender = 1,
                            HouseId = 2,
                            ImagePath = "/images/characters/tyrion-lannister.png",
                            LastEpisodeAppearance = "The Iron Throne",
                            LastName = "Lannister",
                            Nickname = "The Imp",
                            Status = 1
                        });
                });

            modelBuilder.Entity("GameOfThrones.Api.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SigilName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/houses/stark.png",
                            Motto = "Winter is coming",
                            Name = "House Stark",
                            Region = "The North",
                            SigilName = "Direwolf"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/images/houses/lannister.png",
                            Motto = "Hear me roar",
                            Name = "House Lannister",
                            Region = "The Westerlands",
                            SigilName = "Lion"
                        });
                });

            modelBuilder.Entity("GameOfThrones.Api.Models.Character", b =>
                {
                    b.HasOne("GameOfThrones.Api.Models.Character", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameOfThrones.Api.Models.House", "House")
                        .WithMany("Characters")
                        .HasForeignKey("HouseId");

                    b.HasOne("GameOfThrones.Api.Models.Character", "KilledBy")
                        .WithMany()
                        .HasForeignKey("KilledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameOfThrones.Api.Models.Character", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameOfThrones.Api.Models.Character", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("House");

                    b.Navigation("KilledBy");

                    b.Navigation("Mother");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("GameOfThrones.Api.Models.House", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
